name: white_noise
description: "A new Flutter project."

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

  just_audio: ^0.9.36
  #just_audio_background: ^0.0.1-beta.11
  audio_service: ^0.18.13
  yandex_mobileads: ^6.3.0
  #ffmpeg_kit_flutter: 6.0.3
  #path_provider: 2.1.1
  volume_controller: ^2.0.7
  rate_my_app: ^2.0.0
  flutter_riverpod: ^2.5.1
  #permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: 3.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 24

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/img/
    - assets/icons/
    - assets/
  fonts:
    - family: MyFontFamily
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf